title: Cayman theme
description: Cayman is a clean, responsive theme for GitHub Pages.
show_downloads: false
theme: jekyll-theme-cayman
github_repository_url: https://github.com/epfl-ada/ada-2021-project-improvise-adapt-overcome
  